# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tim Moreton
email: info@tmoreton.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tmoreton1
github_username: tmoreton
instagram_username: travelingdeveloper

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  # Build settings

collections:
  trips:
    output: true

contentful:
  spaces:
    - articles: # Jekyll _data folder identifier - Required
        space: gnyu630n9dw2        # Required
        access_token: 7af741d04c6247e32689f6de80d7286812a62b8525272a7273ec695f20216ebf # Required
        cda_query:                 # Optional
          include: 2
          limit: 100
        # content_types:             # Optional
        #   cat: Photo Gallery
        # client_options:            # Optional
        #   api_url: 'preview.contentful.com' # Defaults to 'api.contentful.com' which is Production
        # base_path: articles        # Optional - Defaults to Current directory

# jekyll contentful